### ISSUE TITLE
Trackpad doesn't work

### ISSUE THREAD

**Issue by randy98** [LukaJankovic/10.12-zenbook-ux303u#2]
Sorry, I'm new to GitHub...I'm more used to bitbucket :).  Wasn't sure how to add a comment, so marking as an issue instead.

To get trackpad to work on Sierra on a Zenbook UX303UB, download drivers from: http://forum.osxlatitude.com/index.php?/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/

Then install the prefpane also mentioned in the article or here: http://www.hackintosh.zone/file/997-correct-preference-pane-trackpad-macos-sierra/

**Comment by LukaJankovic** [comment]
Is it working at all? Have you confirmed it works on windows?

**Comment by randy98** [comment]
I don't understand the question.  Yes, it's working now.  
And yes, trackpad works fine under windows 10.  Thanks. --Randy
